name = "matt-ai"
pages_build_output_dir = "pages/dist"
compatibility_date = "2024-05-12"
compatibility_flags = ["nodejs_compat"]
ai = { binding = "AI" }
services = [
    { binding = "BACKEND_WORKER", service = "mattai-worker-preview", environment = "production" },
]

[vars]
NODE_ENV = "development"
TURNSTILE_SITE_KEY = "0x4AAAAAAAQ34m_klLCEVN51"


[env.production]
compatibility_date = "2024-05-12"
compatibility_flags = ["nodejs_compat"]
ai = { binding = "AI" }
services = [
    { binding = "BACKEND_WORKER", service = "mattai-worker", environment = "production" },
]

[env.production.vars]
NODE_ENV = "production"
TURNSTILE_SITE_KEY = "0x4AAAAAAAQ34m_klLCEVN51"


[dev]
local_protocol = "http"
ip = "localhost"
port = 11412
