name = "mattai-worker-preview"
main = "src/index.ts"
compatibility_date = "2024-04-03"
compatibility_flags = ["nodejs_compat", "brotli_content_encoding"]
workers_dev = false
minify = true
ai = { binding = "AI" }
durable_objects.bindings = [
    { name = "QUEUE_CALLBACK_HANDLER", class_name = "QueueCallbackHandler" },
]
migrations = [{ tag = "v1", new_classes = ["QueueCallbackHandler"] }]

[vars]
NODE_ENV = "development"

[placement]
mode = "smart"


[env.production]
name = "mattai-worker"
compatibility_date = "2024-04-03"
compatibility_flags = ["nodejs_compat", "brotli_content_encoding"]
workers_dev = false
minify = true
ai = { binding = "AI" }
durable_objects.bindings = [
    { name = "QUEUE_CALLBACK_HANDLER", class_name = "QueueCallbackHandler" },
]
migrations = [{ tag = "v1", new_classes = ["QueueCallbackHandler"] }]

[env.production.vars]
NODE_ENV = "production"

[env.production.placement]
mode = "smart"


[dev]
local_protocol = "https"
ip = "localhost"
