name = "mattai-worker-development"
main = "src/index.ts"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-03-29"
workers_dev = false
minify = true
ai = { binding = "AI" }

[vars]
NODE_ENV = "development"

[placement]
mode = "smart"

[env.staging]
name = "mattai-worker-staging"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-03-29"
workers_dev = false
minify = true
ai = { binding = "AI" }

[env.staging.vars]
NODE_ENV = "production"


[env.production]
name = "mattai-worker"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-03-29"
workers_dev = false
minify = true

[env.production.vars]
NODE_ENV = "production"

[env.production.ai]
binding = "AI"
