name = "mattai-worker-development"
main = "src/index.ts"
compatibility_date = "2024-01-29"
compatibility_flags = ["nodejs_compat"]
workers_dev = false
minify = true

[vars]
NODE_ENV = "development"

[ai]
binding = "AI"


[placement]
mode = "smart"

[env.staging]
name = "mattai-worker-staging"
compatibility_date = "2024-01-29"
compatibility_flags = ["nodejs_compat"]
workers_dev = false
minify = true

[env.staging.vars]
NODE_ENV = "production"

[env.staging.ai]
binding = "AI"


[env.production]
name = "mattai-worker"
compatibility_date = "2024-01-29"
compatibility_flags = ["nodejs_compat"]
workers_dev = false
minify = true

[env.production.vars]
NODE_ENV = "production"

[env.production.ai]
binding = "AI"
