name = "mattai-worker-preview"
main = "src/index.ts"
compatibility_date = "2024-07-18"
compatibility_flags = ["nodejs_compat"]
workers_dev = false
minify = true
ai = { binding = "AI" }
browser = { binding = "BROWSER" }

[vars]
NODE_ENV = "development"

[placement]
mode = "smart"


[env.production]
name = "mattai-worker"
compatibility_date = "2024-07-18"
compatibility_flags = ["nodejs_compat"]
workers_dev = false
minify = true
ai = { binding = "AI" }
browser = { binding = "BROWSER" }

[env.production.vars]
NODE_ENV = "production"

[env.production.placement]
mode = "smart"


[dev]
local_protocol = "https"
ip = "localhost"
