name: CF Workers Ai Catalog

on:
  push:
    paths:
      - '.github/workflows/ai-catalog.yml'
      - 'shared/workers-ai-catalog.ts'
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  CATALOG_FILE_TS: shared/workers-ai-catalog.ts
  CATALOG_FILE_JSON: shared/workers-ai-catalog.json

jobs:
  regenerate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          disable-sudo: true
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Hit API endpoints and process results
        run: |
          # Get models
          result1=$(curl -s -H "Authorization: Bearer ${{ secrets.WORKERS_AI_API_KEY }}" https://api.cloudflare.com/client/v4/accounts/${{ secrets.CF_ACCOUNT_ID }}/ai/models/search | jq '.result')

          # Group models by task.name and remove the task field from each model
          grouped_models=$(echo "$result1" | jq '
            group_by(.task.name) |
            map({
              (.[0].task.name): {
                id: .[0].task.id,
                description: .[0].task.description,
                models: map(
                  del(.task) |
                  . + {
                    properties: (reduce .properties[] as $prop ({}; .[$prop.property_id] = (
                      if $prop.value | test("^(true|false)$") then ($prop.value | test("true"))
                      elif $prop.value | test("^\\d+$") then ($prop.value | tonumber)
                      else $prop.value
                      end
                    )))
                  }
                )
              }
            }) | add
          ')

          # Get loras
          result2=$(curl -s -H "Authorization: Bearer ${{ secrets.WORKERS_AI_API_KEY }}" https://api.cloudflare.com/client/v4/accounts/${{ secrets.CF_ACCOUNT_ID }}/ai/finetunes/public | jq '.result')

          # Create the final JSON structure
          final_json=$(jq -n --argjson modelGroups "$grouped_models" --argjson loras "$result2" '{"modelGroups": $modelGroups, "loras": $loras}')

          # Create the TypeScript file with a single export
          echo "export const workersAiCatalog = $final_json as const" > ${{ env.CATALOG_FILE_TS }}
          echo "$final_json" > ${{ env.CATALOG_FILE_JSON }}
        shell: bash
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: lts/*
          check-latest: true
          cache: 'npm'
      - run: npm install -D prettier @demosjarco/prettier-config
      - run: npx prettier --write ${{ env.CATALOG_FILE_TS }} ${{ env.CATALOG_FILE_JSON }}
      - name: Git Setup
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - run: git add ${{ env.CATALOG_FILE_TS }}
      - run: git add ${{ env.CATALOG_FILE_JSON }}
      - run: git commit -m "Updated model catalog" || echo "model catalog not touched"
      - run: git push
