name: Pin `node` `latest`

on:
  push:
    branches:
      - '**-latest'
    paths:
      - '.nvmrc'
  pull_request:
    types:
      - opened
    branches:
      - '**-latest'
    paths:
      - '.nvmrc'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  editVersion:
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@f086349bfa2bd1361f7909c78558e816508cdc10 # v2.8.0
        with:
          disable-sudo: true
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        id: sn
        with:
          node-version: latest
          check-latest: true
          cache: 'npm'
      - run: echo "${{ steps.sn.outputs.node-version }}" > .nvmrc
      - name: Git Setup
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - run: git commit .nvmrc -m "Fixed node version" || echo "nv change not needed"
      - run: git push
