name: Pin `node` `lts`

on:
  push:
    branches:
      - 'production'
      - 'staging'
      - 'dev'
      - '**-lts'
    paths:
      - '.nvmrc'
  pull_request:
    types:
      - opened
    branches:
      - 'production'
      - 'staging'
      - 'dev'
      - '**-lts'
    paths:
      - '.nvmrc'
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  editVersion:
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          disable-sudo: true
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        id: sn
        with:
          node-version: lts/*
          check-latest: true
          cache: 'npm'
      - run: echo "${{ steps.sn.outputs.node-version }}" > .nvmrc
      - name: Git Setup
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - run: git commit .nvmrc -m "Fixed node version" || echo "nv change not needed"
      - run: git push
