name: Pin `node` `lts`

on:
  push:
    branches:
      - production
      - preview
      - '**-lts'
    paths:
      - '.nvmrc'
  pull_request:
    types:
      - opened
    branches:
      - production
      - preview
      - '**-lts'
    paths:
      - '.nvmrc'
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  editVersion:
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          disable-sudo: true
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        id: sn
        with:
          node-version: lts/*
          check-latest: true
          cache: 'npm'
      - run: echo "${{ steps.sn.outputs.node-version }}" > pages/.nvmrc
      - name: Git Setup
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - run: git commit .nvmrc -m "Fixed node version" || echo "nv change not needed"
      - run: git push
