name: Split `node` version

on:
  push:
    branches:
      - preview

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  split:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - node-version: 'lts/*'
            branch-suffix: 'lts'
          - node-version: 'latest'
            branch-suffix: 'latest'
    steps:
      - uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
          disable-sudo: true
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          ref: '${{ github.head_ref || github.ref_name }}-${{ matrix.branch-suffix }}'
          fetch-depth: 0
      - name: Git Setup
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Merge from ${{ github.head_ref || github.ref_name }} to ${{ github.head_ref || github.ref_name }}-${{ matrix.branch-suffix }}
        run: git merge -X theirs origin/${{ github.head_ref || github.ref_name }}
      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        id: sn
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
          cache: 'npm'
      - run: echo "${{ steps.sn.outputs.node-version }}" > pages/.nvmrc
      - run: git commit .nvmrc -m "Set version to ${{ matrix.branch-suffix }}" || echo "nv change not needed"
      - run: git push
