name: Publish Worker

on:
  push:
    branches:
      - production
      - preview
    paths:
      - '.github/workflows/publish-worker.yml'
      - 'package*.json'
      - 'worker/package*.json'
      - 'worker/aiTypes/**'
      - 'worker/src/**'
      - 'worker/typechat/**'
      - 'tsconfig.json'
      - 'worker/tsconfig.json'
      - 'worker/wrangler.toml'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose an environment to deploy to:'
        required: true
        default: 'preview'
        type: environment

concurrency:
  group: ${{ github.workflow }}-${{ inputs.environment || github.ref_name }}
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment || github.ref_name }}
    steps:
      - uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
        with:
          disable-sudo: true
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: lts/*
          check-latest: true
          cache: 'npm'
      - run: npm ci --include-workspace-root --workspace worker
      # For some reason tsc doesn't start looking in the folder, but 1 up
      - run: npx tsc --project aiTypes/tsconfig.json
        working-directory: worker/aiTypes
      - run: npm -w worker run build
      - run: echo "wrangler_version=$(npm ls wrangler --depth=0 --json | jq -r '.dependencies.wrangler.version')" >> $GITHUB_OUTPUT
        id: npm_wrangler_version
      - uses: cloudflare/wrangler-action@a84dcc6dd36c8769fbff7e622308c8050fc41f4f # v3.5.0
        id: wrangler
        with:
          wranglerVersion: ${{ steps.npm_wrangler_version.outputs.wrangler_version }}
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          environment: ${{ vars.ENVIRONMENT != 'preview' && vars.ENVIRONMENT || '' }}
          workingDirectory: worker
          vars: |
            GIT_HASH
        env:
          GIT_HASH: ${{ github.sha }}
